language: node_js
sudo: false
node_js:
  - stable
install:
  - npm install
script:
  - npm run test
  - npm run cover
  - REACT_APP_API_URL=$api_url REACT_APP_API_ACCESS_KEY=$api_key npm run build
after_script:  
  - COVERALLS_REPO_TOKEN=$coveralls_token npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master