/***************
 * API ACTIONS *
 ***************/

// Get all
export const API_REQUEST_ALL_OPERATION = 'API_REQUEST_ALL_OPERATION';
export type API_REQUEST_ALL_OPERATION = typeof API_REQUEST_ALL_OPERATION;

export const API_RESPONSE_ALL_OPERATION = 'API_RESPONSE_ALL_OPERATION';
export type API_RESPONSE_ALL_OPERATION = typeof API_RESPONSE_ALL_OPERATION;

// Get
export const API_REQUEST_GET_OPERATION = 'API_REQUEST_GET_OPERATION';
export type API_REQUEST_GET_OPERATION = typeof API_REQUEST_GET_OPERATION;

export const API_RESPONSE_GET_OPERATION = 'API_RESPONSE_GET_OPERATION';
export type API_RESPONSE_GET_OPERATION = typeof API_RESPONSE_GET_OPERATION;

// Add
export const API_REQUEST_ADD_OPERATION = 'API_REQUEST_ADD_OPERATION';
export type API_REQUEST_ADD_OPERATION = typeof API_REQUEST_ADD_OPERATION;

export const API_RESPONSE_ADD_OPERATION = 'API_RESPONSE_ADD_OPERATION';
export type API_RESPONSE_ADD_OPERATION = typeof API_RESPONSE_ADD_OPERATION;

// Remove
export const API_REQUEST_REMOVE_OPERATION = 'API_REQUEST_REMOVE_OPERATION';
export type API_REQUEST_REMOVE_OPERATION = typeof API_REQUEST_REMOVE_OPERATION;

// Update
export const API_REQUEST_EDIT_OPERATION = 'API_REQUEST_EDIT_OPERATION';
export type API_REQUEST_EDIT_OPERATION = typeof API_REQUEST_EDIT_OPERATION;

// Common response
export const API_RESPONSE_OPERATION = 'API_RESPONSE_OPERATION';
export type API_RESPONSE_OPERATION = typeof API_RESPONSE_OPERATION;

// Common error
export const API_ERROR_OPERATION = 'API_ERROR_OPERATION';
export type API_ERROR_OPERATION = typeof API_ERROR_OPERATION;

/***************
 * UI ACTIONS *
 ***************/

// Request edit operation
export const UI_EDIT_OPEN_OPERATION = 'UI_EDIT_OPEN_OPERATION';     // TODO: separate api and ui actions!!
export type UI_EDIT_OPEN_OPERATION = typeof UI_EDIT_OPEN_OPERATION;

// Save operation after edit
export const UI_EDIT_SAVE_OPERATION = 'UI_EDIT_SAVE_OPERATION';
export type UI_EDIT_SAVE_OPERATION = typeof UI_EDIT_SAVE_OPERATION;

// Close operation edit
export const UI_EDIT_CLOSE_OPERATION = 'UI_EDIT_CLOSE_OPERATION'; 
export type UI_EDIT_CLOSE_OPERATION = typeof UI_EDIT_CLOSE_OPERATION;