// Get all
export const REQUEST_ALL_OPERATIONS = 'REQUEST_ALL_OPERATIONS';
export type REQUEST_ALL_OPERATIONS = typeof REQUEST_ALL_OPERATIONS;

export const RECEIVE_ALL_OPERATIONS = 'RECEIVE_ALL_OPERATIONS';
export type RECEIVE_ALL_OPERATIONS = typeof RECEIVE_ALL_OPERATIONS;

// Get
export const REQUEST_OPERATION = 'REQUEST_OPERATION';
export type REQUEST_OPERATION = typeof REQUEST_OPERATION;

export const RECEIVE_OPERATION = 'RECEIVE_OPERATION';
export type RECEIVE_OPERATION = typeof RECEIVE_OPERATION;

// Add
export const REQUEST_ADD_OPERATION = 'REQUEST_ADD_OPERATION';
export type REQUEST_ADD_OPERATION = typeof REQUEST_ADD_OPERATION;

export const RESPONSE_ADD_OPERATION = 'RESPONSE_ADD_OPERATION';
export type RESPONSE_ADD_OPERATION = typeof RESPONSE_ADD_OPERATION;

// Remove
export const REQUEST_REMOVE_OPERATION = 'REQUEST_REMOVE_OPERATION';
export type REQUEST_REMOVE_OPERATION = typeof REQUEST_REMOVE_OPERATION;

// Update
export const REQUEST_UPDATE_OPERATION = 'REQUEST_UPDATE_OPERATION';
export type REQUEST_UPDATE_OPERATION = typeof REQUEST_UPDATE_OPERATION;

// Common response
export const RESPONSE_OPERATION = 'RESPONSE_OPERATION';
export type RESPONSE_OPERATION = typeof RESPONSE_OPERATION;

// Common error
export const RESPONSE_ERROR_OPERATION = 'RESPONSE_ERROR_OPERATION';
export type RESPONSE_ERROR_OPERATION = typeof RESPONSE_ERROR_OPERATION;

// Request edit operation
export const REQUEST_EDIT_OPERATION = 'REQUEST_EDIT_OPERATION';     // TODO: separate api and ui actions!!
export type REQUEST_EDIT_OPERATION = typeof REQUEST_EDIT_OPERATION;

// Save operation after edit
export const SAVE_EDIT_OPERATION = 'SAVE_EDIT_OPERATION';
export type SAVE_EDIT_OPERATION = typeof SAVE_EDIT_OPERATION;

// Close operation edit
export const CLOSE_EDIT_OPERATION = 'CLOSE_EDIT_OPERATION'; 
export type CLOSE_EDIT_OPERATION = typeof CLOSE_EDIT_OPERATION;