// Get all
export const REQUEST_ALL_OPERATIONS = 'REQUEST_ALL_OPERATIONS';
export type REQUEST_ALL_OPERATIONS = typeof REQUEST_ALL_OPERATIONS;

export const RECEIVE_ALL_OPERATIONS = 'RECEIVE_ALL_OPERATIONS';
export type RECEIVE_ALL_OPERATIONS = typeof RECEIVE_ALL_OPERATIONS;

// Get
export const REQUEST_OPERATION = 'REQUEST_OPERATION';
export type REQUEST_OPERATION = typeof REQUEST_OPERATION;

export const RECEIVE_OPERATION = 'RECEIVE_OPERATION';
export type RECEIVE_OPERATION = typeof RECEIVE_OPERATION;

// Add
export const REQUEST_ADD_OPERATION = 'REQUEST_ADD_OPERATION';
export type REQUEST_ADD_OPERATION = typeof REQUEST_ADD_OPERATION;

export const RESPONSE_ADD_OPERATION = 'RESPONSE_ADD_OPERATION';
export type RESPONSE_ADD_OPERATION = typeof RESPONSE_ADD_OPERATION;

// Remove
export const REQUEST_REMOVE_OPERATION = 'REQUEST_REMOVE_OPERATION';
export type REQUEST_REMOVE_OPERATION = typeof REQUEST_REMOVE_OPERATION;

// Update
export const REQUEST_UPDATE_OPERATION = 'REQUEST_UPDATE_OPERATION';
export type REQUEST_UPDATE_OPERATION = typeof REQUEST_UPDATE_OPERATION;

// Common response
export const RESPONSE_OPERATION = 'RESPONSE_OPERATION';
export type RESPONSE_OPERATION = typeof RESPONSE_OPERATION;