// Common set
export const SET_APPLICATION_SETTING = 'SET_APPLICATION_SETTING';
export type SET_APPLICATION_SETTING = typeof SET_APPLICATION_SETTING;

// Update settings
export const UPDATE_ALL_APPLICATION_SETTINGS = 'UPDATE_ALL_APPLICATION_SETTINGS';
export type UPDATE_ALL_APPLICATION_SETTINGS = typeof UPDATE_ALL_APPLICATION_SETTINGS;